import { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'RSD Workshop App',
    description: 'Generated by create next app',
    viewport: 'width=device-width, initial-scale=1',
    icons: {
        icon: '/favicon2.ico',
    },
}

export default function RootLayout({
   // Layouts must accept a children prop.
   // This will be populated with nested layouts or pages
   children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body>
        {children}
        </body>
        </html>
    )
}
