import { Metadata } from 'next'
import {Provider} from "@/components/Provider/Provider";

export const metadata: Metadata = {
    title: 'RSD Workshop App', // title of the application shown in the browser tab
    description: 'Generated by create next app',
    viewport: 'width=device-width, initial-scale=1',
    icons: {
        icon: '/favicon.ico', // favicon shown next to the title in the broswer tab
    },
}

export default function RootLayout({
   // Layouts must accept a children prop.
   // This will be populated with nested layouts or pages
   children,
}: {
    children: React.ReactNode
}) {
    // the Provider component wraps all children components in the body of our website and applies the theme to them
    return (
        <html lang="en">
        <body>
        <Provider>
            {children}
        </Provider>
        </body>
        </html>
    )
}
